"use client";
import { store } from "@/stores";
import "./globals.css";

import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import NotificationBar from "@/Component/NotificationBar";
import NavbarComponent from "@/Component/Navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <Provider store={store}>
          <NotificationBar />
          <NavbarComponent />
          {children}
        </Provider>
      </body>
    </html>
  );
}
